title: Aquele Blog muito à frente!
email: aqueleblogmuitoafrente@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Um blog de sátira social sem papas na língua
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Author settings
author: Humberto Vaz # add your name
author-pic: humberto-vaz.png
about-author: Olá dou-me pelo nome Humberto no Inverno e Zé Roberto no Verão, nas outras duas estações ainda não pensei muito sobre isso

# Contact links
email: aqueleblogmuitoafrente@gmail.com # Add your Email address
phone: # Add your Phone number
# Why would you have it on your website?
#website: # Add your website, do not add http://
linkedin: # Add your Linkedin handle
github: humbertovaz # Add your Github handle
twitter: '@humbertojvaz' # Add your Twitter handle
# Why not the facebook page of it?
facebook: aqueleblogmuitoafrente # Add your Facebook handle
instagram: # Add your Instagram handle
pinterest: # Add your Pinterest handle

# Newsletter
mailchimp: # Add your MailChimp form identifier.

# Disqus
discus_identifier:  # Add your discus identifier

# Tracker
analytics: # Google Analytics

# Paginate
paginate: 12
paginate_path: /page:num/

# Build settings
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
